// Autogenerated file by tevmc @ $timestamp

const {addApiServer, addIndexer} = require("./definitions/ecosystem_settings");

module.exports = {
    apps: [
        addIndexer('$name'),
        addApiServer('$name', 1)
    ]
};
